### ISSUE TITLE
Allow some way to confirm naming

### ISSUE THREAD

**Issue by bigbrainiac10** [DevotedMC/WordBank#8]
Allow some way to confirm naming so accidental naming doesn't occur.

Perhaps double right click to confirm?

**Comment by ProgrammerDan** [comment]
lol just don't carry around XP bottles

**Comment by ProgrammerDan** [comment]
I'll see about it, just detracts from ease of use ...

**Comment by ProgrammerDan** [comment]
Tested and working on devotest. Doubletap the enchant table to enchant. 10 second "window" by default.
